### ISSUE TITLE
TypeError: this.position.add is not a function

### ISSUE THREAD

**Issue by SkyzohKey** [pixelpicosean/Panda-NinjaPhysics#2]
This happens with the demo code:

``` es6
// Create a body like you've always done
var circleBody = new physics.Body({
  position: { x: 120, y: 120 },
  shape: new physics.Circle(40),
  mass: 1, // will fall
  collisionGroup: 1,
  collideAgainst: [2]
});

var rectBody = new physics.Body({
  position: { x: 100, y: 100 },
  shape: new physics.Rectangle(40, 40),
  collisionGroup: 2
});

// Add them to world and it just works
circleBody.addTo(this.world);
rectBody.addTo(this.world);
```

`core.scene.world` seems to doesn't exists, too.

**Comment by pixelpicosean** [comment]
The position object you passed in replaced the `physics.Body.position`. Try `circleBody.position.set(120, 120)` instead.

**Comment by pixelpicosean** [comment]
`core.scene` is not set in `constructor` where you can always use `this` instead. And you can refer to `core.scene` in other methods of scene such as `awake` and `update`.

**Comment by SkyzohKey** [comment]
What's the `awake` method for ? I'm french and can't understand the word :p

**Comment by pixelpicosean** [comment]
Also the instances of `Scene` are only created once and you should clean up and reset through `awake` and `freeze` methods. I recommend you reuse objects as much as possible since GC eat up memory and may crash the browser during switching between scenes(this is very common when I use Panda.js).

**Comment by SkyzohKey** [comment]
I still get this weird error: `TypeError: this.circleBody.position.set is not a function`
Here's a copy of my code. Sorry for being noob, i'm studying lesser-panda x)

```
main.js
```

``` es6
import engine from 'engine/core';
import Scene  from 'engine/scene';
import PIXI   from 'engine/pixi';
import Timer  from 'engine/timer';
import audio  from 'engine/audio';
import loader from 'engine/loader';
import 'engine/timeline';

// Plugins imports.
import physics from 'plugins/ninja-physics';

// Game imports.
import 'game/loading';

// Load textures
loader.addAsset('gold_1.png', 'gold_1');
loader.addAsset('gold_2.png', 'gold_2');
loader.addAsset('gold_3.png', 'gold_3');
loader.addAsset('gold_4.png', 'gold_4');
// Load bitmap fonts
loader.addAsset('KenPixel.fnt');
// Load audio files
loader.addSound(['boot.m4a', 'boot.ogg'], 'bgm');

PIXI.SCALE_MODES.DEFAULT = PIXI.SCALE_MODES.NEAREST;

class Main extends Scene {
  constructor() {
    super();

    // Create a body like you've always done
    this.circleBody = new physics.Body({
      position: { x: 120, y: 120 },
      shape: new physics.Circle(40),
      mass: 1, // will fall
      collisionGroup: 1,
      collideAgainst: [2]
    });

    this.rectBody = new physics.Body({
      position: { x: 100, y: 100 },
      shape: new physics.Rectangle(40, 40),
      collisionGroup: 2
    });

  }
  awake() {
    // Add them to world and it just works
    this.circleBody.position = {x: 120, y:120};
    this.circleBody.addTo(engine.scene.world);
    this.rectBody.addTo(engine.scene.world);
  }
};
engine.addScene('Main', Main);
engine.startWithScene('Loading');
```

**Comment by pixelpicosean** [comment]
Do not override the position while creating a Body instance:

``` javascript
// Create a body like you've always done
    this.circleBody = new physics.Body({
      // Please remove this line, since Body.position is an instance of Vector, you replaced it with a pure object
      // position: { x: 120, y: 120 },
      shape: new physics.Circle(40),
      mass: 1, // will fall
      collisionGroup: 1,
      collideAgainst: [2]
    });
    // This works
    this.circleBody.position.set(120);

    this.rectBody = new physics.Body({
      // Remove this line too
      // position: { x: 100, y: 100 },
      shape: new physics.Rectangle(40, 40),
      collisionGroup: 2
    });
    this.rectBody.position.set(100);
```

And set position like this:

``` javascript
this.circleBody.position.set(120);
```

Also you may not want to call `addTo` multiply times (inside the update method), althought it won't cause any issues.

**Comment by pixelpicosean** [comment]
Let me explain the lifecycle of `Scene`:
1. `constructor` is called while the scene is set for the first time. You are recommend to create object instances for later use here.
2. `awake` means the scene is activated and will be use next frame.
3. `preUpdate`, `update`, `postUpdate` is called during updating in turn.
4. `freeze` is called before switching to other scenes.

**Comment by pixelpicosean** [comment]
I'd recommend you to use built-in `physics` module instead since I am planning to make some changes to this plugin and merge it into the built-in one.

**Comment by SkyzohKey** [comment]
Yeah, but their is no doc. Is it planned to generated some doc using jsdoc or something ? :p

**Comment by pixelpicosean** [comment]
Yep, I am thinking about generating docs which should not be hard since almost every method and property is well documented.
You can send PR or read those inline documents before I finished doc generating task.

**Comment by SkyzohKey** [comment]
Yep, thanks for using time answering my doubts. :)

**Comment by pixelpicosean** [comment]
You're welcome :smile: 
Also thank you for trying LesserPanda. I have a lot of plans but only some of them are finished(you already see there're an WIP editor, some CLI commands are not finished and engine itself needs some refactors). It may grow much faster if there're more contributors.

**Comment by SkyzohKey** [comment]
I'll experiments and (probably) contribute, don't worries. :)
